id: ID250B7D8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-03-31T05:43:09+00:00'
last_modified: '2022-06-16T05:10:18.680317+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN22346
  title: ཏུན་ཧོང་ཡིག་ཚང་ཁྲོད་ཀྱི་ས་ལུ་ལྗང་པ་དང་རྡོ་རྗེ་གཅོད་པའི་མཆན་འགྲེལ།
  author: ''
  base:
    076A:
      image_group_id: I4CN10111
      title: ''
      total_pages: ''
      order: 1
      base_file: 076A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
